redCOMPONENT-COM/redCORE

.travis.yml, .travis/wait4selenium.sh
This pull improves the waiting time for Selenium Server to load
=> QA-8 wait for Selenium server to load

component/admin/models/webservice.php, libraries/redcore/component/helper.php, libraries/redcore/translation/helper.php
Some more I stumbled upon when navigating through the different functions
=> Moved import inclusion to avoid error on web service functions

component/admin/layouts/sidebar.bs3.php, component/admin/layouts/sidebar.php, component/admin/views/config/view.html.php, libraries/redcore/component/helper.php, libraries/redcore/html/media.php, redcore.xml
[+] introduced attribute defaultFramework with which you can set configuration (and other views in the future) to specific framework, default is redCORE framewok and at the moment it is bootstrap3
=> REDCORE-312_config_view_should_be_optional_bootstrap2

libraries/redcore/html/media.php, libraries/redcore/redcore.xml, modules/site/mod_redcore_language_switcher/mod_redcore_language_switcher.xml, plugins/system/redcore/redcore.xml, redcore.xml, redcore_copy_mandatory.xml
[*] This will make sure that submodule is initialized and if not, it will try to update it first, then if it is still not present it will fail.
[-] Fixed Media Framework default value
=> Redcore 332 fix issues with mvcoverride submodule

libraries/redcore/api/hal/hal.php, libraries/redcore/api/hal/transform/none.php, libraries/redcore/language/en-GB/en-GB.lib_redcore.ini, libraries/redcore/redcore.xml, media/redcore/webservices/joomla/administrator.contact.1.0.0.xml, media/redcore/webservices/joomla/site.contact.1.0.0.xml, modules/site/mod_redcore_language_switcher/mod_redcore_language_switcher.xml, plugins/system/redcore/redcore.php, plugins/system/redcore/redcore.xml, redcore.xml
[*] Execution of webservice is now wrapped up so it will put warnings and notices inside json _messages container
[*] It will now show 404 Not found in json output if no item is found and not empty object
[+] Now we can define Primary field in Read Item group in webservice XML file that will be used as ID for the read item. If no primary key is defined, it will use ID as default (was previous functionality)
[+] Added "None" as transform type for fields that you do not want to transform at all (like Files)
=> Rsbtb 2024 make any primary field possible to fetch an item

component/admin/views/webservice/tmpl/default_read.php
[*] Added Default value on the list of read list and item webservice editor thus fixing the import from database table view
=> RSBTB-2024_load_field_from_db_fix

libraries/redcore/api/hal/hal.php, media/redcore/webservices/joomla/administrator.contact.1.0.0.xml
- fixes bug for authorization
+ checks authorization for read item for keys if primary key is not default id
=> Redcore 340 read item permissions check bug

component/admin/layouts/translation/params.php, component/admin/views/translations/tmpl/default.php, libraries/redcore/redcore.xml, libraries/redcore/translation/helper.php, media/redcore/translations/com_categories/categories.xml, media/redcore/translations/com_modules/modules.xml, media/redcore/translations/com_plugins/plugins.xml, modules/site/mod_redcore_language_switcher/mod_redcore_language_switcher.xml, plugins/system/redcore/redcore.php, plugins/system/redcore/redcore.xml, redcore.xml
+ now we can translate plugins
=> Redcore 272 add plugin translation capability

libraries/redcore/api/hal/model/item.php, libraries/redcore/api/hal/table/table.php
+ with this we can have anything as primary key instead of int only
=> REDCORE-344_joomla_only_accepts_int_as_primary_key

.travis.yml
If Travis passes without issues we are good to merge.
=> REDCORE-310 update to latest selenium server

README.md
=> Add Download Latest link to readme.md

manual/en-US/chapters/framework/overview.md, manual/en-US/chapters/introduction.md, manual/en-US/menu.md
This pull adds a download link to latest redCORE.
Also redCORE is not anymore just a Framework for building extensions but a Joomla Extension that adds webservices, translation feature, MVC override and a Framework for building extensions.  This is now clarified in the documentation
=> REDCORE-355 Adds redCORE download link in documentation

.travis.yml
=> Regenerate and encript travis-slack notification

tests/acceptance/01-InstallJoomlaCept.php, tests/acceptance/02-InstallExtensionCept.php, tests/acceptance/03-CheckForWarningsAndNoticesCept.php
Wait for travis to reply on this one
=> REDCORE-383 Adding Codeception Warnings and Notices checker

.travis.yml
=> REDCORE-383 Testing Selenium Server

install.php
If your package name is something like `Pkg_MipaywayInstallerScript` (note the `Pkg` prefix) the manifest won't be loaded properly because `Pkg` != `pkg`. This forces the lowercase comparison.
Additionally this adds manifest cache so it only needs to be loaded once. In my checks this saves like 6-7 loads.
=> [fix] force strtolower comparison when loading package manifest

install.php
In https://github.com/redCOMPONENT-COM/redCORE/pull/482 the condition I used is wrong
=> [fix] wrong condition

.gitignore, .travis.yml, RoboFile.php
This change will store Selenium output in a .log file, and afterwards it will print it in Travis console for easier debugging
cc: @puneet0191, @jatitoam
=> REDCORE-386 store selenium log

.travis.yml, RoboFile.php
Travis will check that this and all our other Extensions have the latest version of our Automated Tasks based in Robo.li
=> REDCORE-390 Add versioning to Robo file in Travis

.travis.yml
This is a test to remove fluxbox errors in Travis
=> REDCORE-388 add time for fluxbox to start

RoboFile.php
@javigomez requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/redCOMPONENT-COM/redCORE/
=> Scrutinizer Auto-Fixes

.travis.yml
see details at the issue description
=> REDCORE-392 fix Slack reports

component/admin/controllers/config.php
Otherwise strings won't get resolved, resulting in just the key to the actual string value being printed out.
=> REDCORE-397 Added loading of language files from other components

component/admin/models/forms/webservice_defaults.xml, component/admin/updates/1.5.5.php, libraries/redcore/api/soap/operation/operation.php, libraries/redcore/bootstrap.php, libraries/redcore/layouts/webservice/documentationoperation/example.php, libraries/redcore/menu/menu.php, libraries/redcore/redcore.xml, media/redcore/webservices/joomla/administrator.contact.1.0.0.xml, media/redcore/webservices/joomla/site.contact.1.0.0.xml, modules/site/mod_redcore_language_switcher/helper.php, modules/site/mod_redcore_language_switcher/mod_redcore_language_switcher.xml, plugins/redpayment/paypal/paypal.xml, plugins/system/redcore/redcore.php, plugins/system/redcore/redcore.xml, redcore.xml
REDCORE-389_menu_not_translated HSSMT-12 REDCORE-348
=> Redcore 389 menu not translated

build.properties.dist, libraries/redcore/database/sqlparser/positioncalculator.php
No issue has been filed on this, as none had been created to my knowledge.
This commit fixes a minor performance issue in sqlparser, and additionally fixes the long broken link in build.properties.dist.
=> Fix minor bugs and performance issues.

tests/acceptance/administrator/03-CheckForWarningsAndNoticesCept.php, tests/acceptance/administrator/04-ActivateDefaultWebservicesWithBasicAuthenticationCept.php
this should avoid false positives as in: https://travis-ci.org/redCOMPONENT-COM/redCORE/jobs/68277862
See documentation at https://docs.joomla.org/Testing_Joomla_Extensions_with_Codeception#How_much_time_should_I_wait_for_an_Element_or_Text.3F
=> REDCORE-269 increase waiting times in tests

.travis.yml
Reverts redCOMPONENT-COM/redCORE#544
=> Revert "Test travis env"

.gitignore, tests/api/administrator.contact.1.0.0.Cest.php
I found this interesting article http://stackoverflow.com/questions/9169081/rest-apis-custom-http-headers-vs-url-parameters
I have moved all params to URL that is the place were they should be
=> REDCORE-269 Update contact webservice test

composer.lock, tests/acceptance/administrator/03-CheckForWarningsAndNoticesCept.php, tests/acceptance/administrator/04-ActivateDefaultWebservicesWithBasicAuthenticationCept.php, tests/acceptance/uninstall/ZZ-UninstallExtensionCept.php
this pull https://github.com/joomla/joomla-cms/pull/7490 changed the Joomla Administrator interface. I'm updating the tests accordingly.
=> Update JoomlaBrowser and changes in Joomla interface

libraries/redcore/api/soap/operation/operation.php
=> RSBTB-2291 Allowed to return different PKs than the ones that were sent during read item operation

libraries/redcore/translation/helper.php
Fix bug, when redcore always work with translations and can`t disabled it.
=> RSBTB-2426 #comment Fix translate flag

libraries/redcore/api/hal/hal.php
this will also fix the same problem we had today with false being without the quotes for required filed
=> RSBTB-2549_required_field_accept_zero

component/admin/views/config/tmpl/edit_configuration.php, libraries/redcore/database/sqlparser/sqlcreator.php, libraries/redcore/redcore.xml, modules/site/mod_redcore_language_switcher/mod_redcore_language_switcher.xml, plugins/redpayment/paypal/paypal.xml, plugins/system/redcore/redcore.xml, redcore.xml
also added ->renderField(); as discussed for adding showon support option
=> REDCORE-437_problem_with_ordering_in_translations

libraries/redcore/model/list.php
There is an issue that allows that list models filters & list options can be changed/used by any visitor. This pull request ensures that the filter form:
* Allows only filters and list options that are present in the filter form.
* Validates filters&list data with any validation rule that the form defines inside
Logout / kill any session open. On a view that uses searchtools try to set filters present in the model but not exposed in the filter form.
Example:
http://sample-site/products?filter[featured]=true
You will need to add a $query->dump() on the model list to see the query being executed.
**Before applying this PR:** you will see that filters / list options are applied
**After this PR:** Only filters in the filter form are successfully applied
Also check that pagination works …
=> Ensure that only filterForm filters are used in list models

libraries/redcore/html/rgrid.php
Current canges allow adding style changes for rgrid.action buttons http://screencast.com/t/nr8dXRRiz
=> Add button class as function value in rgrid.action

composer.json, composer.lock, tests/acceptance.suite.dist.yml, tests/acceptance/administrator/04-ActivateDefaultWebservicesWithBasicAuthenticationCept.php, tests/api.suite.dist.yml, tests/api/administrator.contact.1.0.0.soap.Cest.php
This is a test to see if TravisCI passes
This pull includes the API tests for the SOAP layer. It uses Com_contacts soap webservice to ensure that the SOAP webservices work all the time.
=> RSBTB-2898 Soap tests

.travis.yml
please see Slack for more info
=> QA-31 [tests] update report system

.gitignore, tests/_support/AcceptanceTester.php, tests/_support/ApiTester.php, tests/_support/FunctionalTester.php, tests/_support/UnitTester.php
Those are used to add common actions to tests
=> Unignore codeception *Tester.php files

tests/acceptance/administrator/03-CheckForWarningsAndNoticesCept.php, tests/acceptance/install/01-InstallJoomlaCest.php, tests/acceptance/install/02-InstallExtensionCest.php
Also removes statistics message in administrator
This improvements were elaborated during #664 tests
=> [tests] Improve locators when installing

extensions/libraries/redcore/html/rbootstrap.php
Fixes a code style issue reported by travis:
=> [tests] fix code style issue

README.md
I have changed Travis setting to only execute on PULL REQUESTS and do not on PUSH events
I'm going to merge my self this pull to see if it works
=>  REDCORE-473 [tests] avoid executing travis on push

build/gulp-redcore/components/redcore.js, build/gulp-redcore/libraries/redcore.js, build/gulp-redcore/modules/site/redcore_langswitcher.js, build/package.json
see https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md
=> gulp script properly combine streams in tasks

docs/gh-pages/manual/en-US/chapters/soapClient.md, docs/gh-pages/manual/en-US/chapters/webserviceClient.md, docs/gh-pages/manual/en-US/menu.md, extensions/libraries/redcore/api/oauth2/oauth2.php, extensions/libraries/redcore/api/soap/transform/base.php, extensions/libraries/redcore/api/soap/wsdl.php, extensions/libraries/redcore/webservices/base.php, extensions/libraries/redcore/webservices/soap.php, extensions/libraries/redcore/webservices/webservice.php, extensions/redcore.xml
+ set language for SOAP readItem operation to optional
+ dump 2+ weeks old tokens for oAuth2
+ set link to redcore configuration from the joomla menu directly to the configuration page
=> Redcore 492 create classes for webservices and soap

extensions/libraries/redcore/layouts/pagination/link.php
it's nothing, but some people are complaining about it...
=> [fix] updated confusing pagination icons

extensions/libraries/redcore/language/da-DK/da-DK.lib_redcore.ini, extensions/libraries/redcore/language/en-GB/en-GB.lib_redcore.ini, extensions/libraries/redcore/layouts/pagination/link.php, extensions/libraries/redcore/layouts/pagination/links.php, extensions/libraries/redcore/pagination/pagination.php
because sometimes life is too short...
=> [imp] Added buttons to fast forward/backward 10 pages

extensions/webservices/joomla/site.users.1.1.0.php
As discussed, the access token will now be set to expired once the user has been authorized.
=> REDCORE-511 Add an authentication function to the user web service

extensions/libraries/redcore/api/payment/helper.php, extensions/libraries/redcore/api/payment/plugin/base.php, extensions/libraries/redcore/api/payment/plugin/helper/payment.php
also require
https://github.com/redCOMPONENT-COM/vanir/pull/4415
https://github.com/redCOMPONENT-COM/redCOREPLUGINS/pull/16/files
https://bitbucket.org/redwebdk/kvasir-sc-sound/pull-requests/99/vnr-4036-comment-new-changes-for-payment/diff
=> VNR-4063 #comment new payment changes

extensions/components/com_redcore/admin/controllers/payment.php, extensions/components/com_redcore/admin/models/translation.php, extensions/components/com_redcore/admin/models/webservices.php, extensions/components/com_redcore/admin/views/payment_configurations/view.html.php, extensions/libraries/redcore/api/hal/hal.php, extensions/libraries/redcore/api/hal/helper.php, extensions/libraries/redcore/api/oauth2/Storage/DynamoDB.php, extensions/libraries/redcore/api/oauth2/oauth2.php, extensions/libraries/redcore/api/payment/plugin/helper/payment.php, extensions/libraries/redcore/api/soap/helper.php, extensions/libraries/redcore/database/sqlparser/positioncalculator.php, extensions/libraries/redcore/database/sqlparser/sqlparser.php, tests/composer.lock
not done yet
current code is unused
=> scrutinizer_issue_1

extensions/components/com_redcore/admin/controllers/config.php, extensions/components/com_redcore/admin/models/translation_tables.php, extensions/components/com_redcore/admin/views/oauth_clients/view.html.php, extensions/components/com_redcore/admin/views/payment_configurations/view.html.php, extensions/components/com_redcore/admin/views/payments/view.html.php, extensions/components/com_redcore/admin/views/translation_tables/view.html.php, extensions/components/com_redcore/admin/views/translations/view.html.php, extensions/components/com_redcore/admin/views/webservices/view.html.php, extensions/libraries/redcore/controller/form.php, extensions/libraries/redcore/factory/factory.php, extensions/libraries/redcore/html/html.php, extensions/libraries/redcore/html/media.php, extensions/libraries/redcore/html/rbootstrap.php, extensions/libraries/redcore/html/rjquery.php, extensions/libraries/redcore/joomla/form/field.php, extensions/libraries/redcore/joomla/layout/file.php, extensions/libraries/redcore/layouts/pagination/link.php, extensions/libraries/redcore/model/admin.php, extensions/libraries/redcore/model/list.php, extensions/libraries/redcore/model/model.php, extensions/libraries/redcore/pagination/pagination.php, extensions/libraries/redcore/translation/helper.php, extensions/plugins/system/redcore/redcore.php, tests/RoboFile.ini.dist
since we have removed depricated methods in updating to joomla 7.1 PR, we introduced errors, the old sites are crashing after update because there is no isClient method yet prior to Joomla 3.7
This is something independent that works for all versions
=> REDCORE-527 fix is client for older joomla versions

extensions/libraries/redcore/layouts/modal/dialog.bs3.php
There were issues in both vanir and redCORE.
=> VNR-4547v2 - Error when placing an offer

extensions/libraries/redcore/table/table.php
it currently doesn't work, as asset name can be different from $this->_tbl, which is used to get the fields... So, it leads to incoherent data in table.
=> [fix] fixed updateSchema

extensions/install.php, extensions/libraries/redcore/component/helper.php, extensions/redcore.xml
Updated install.php to use RuntimeExceptions
Refactored RComponentHelper::checkComponentRequirements()
The logic has been refactored to make it a little easier to scale up later and make better use of SimpleXML
The XML syntax used has been changed to make it more flexible.
=> Refactored requirements validation

build/media/libraries/redcore/media/redcore/less/component.less
Permisions tab was too large in small screen resolutions
=> REDCORE-539 Added styling overrides for permissions tab
