libraries/redcore/view/csv.php
Function to be overridden in other classes. Used e.g. to replace the currency separator dynamically, since it's stored with just a `.` regardless of region.
Related to `RSTBT-1911`.
=> REDCORE-328 Added preprocessing function for fields in report

libraries/redcore/api/hal/hal.php
needed because some models on read item returns instance of the object with a JRegistry params and tags, so it is not possible to distinct if the item is found or not. Previous attempt with primary keys is not always best option because model does not have to return primary key field in the object. This will check if the model have put error message when trying to get the item
=> Rsbtb 2024 check for read item fix

libraries/redcore/redcore.xml, libraries/redcore/translation/content/helper.php, modules/site/mod_redcore_language_switcher/mod_redcore_language_switcher.xml, plugins/system/redcore/redcore.xml, redcore.xml
This methods should be static to avoid this error:
```
( ! ) Strict standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method RTranslationContentHelper::saveUrlParams() should not be called statically in /var/www/translate/administrator/components/com_redcore/models/translation.php on line 253
```
=> REDCORE-350 fix Strict standards error calling statically a non static method

install.php
Try to use redCORE with a package structure. It won't get installed because the `if ($type == 'component')` check.
I'm not sure how this will affect other extensions. Technically it shouldn't break anything but I think someone needs to review it.
=> [fix] redCORE not installed with packages

install.php
There is a bug when installing a package that contains 2 components that depend on redCORE (e.g. to prevent it from being uninstalled when any of them are still there).
On the first pass `RComponentHelper` will be loaded from the install folder but in the second pass (when installing the second component) the file will be found already installed so require_once isn't enough to ensure that it's not loaded twice.
=> [fix] a package cannot install 2 components with redCORE as dependency

libraries/redcore/table/table.php
I think it doesn't make a lot of sense that a method of a class that is really abstract cannot be overriden in child classes. 
Of course you can bypass if by overriding `delete()` method in your child class and calling another function from there (like `doMyDelete()`) but it just makes things harder.
=> [imp] allow to override doDelete on child classes

RoboFile.php
Now the run:test command is able to list tests inside folders under a suite:
=> REDCORE-269 improve run:test command

tests/api/administrator.contact.1.0.0.Cest.php
I'm updating Contacts test name to match the standard created at redSHOPB2B. This way tests have the  same name as the webservice.
Also, methods have been renamed to a more simple way.
=> REDCORE-269 standarise api tests names

libraries/redcore/layouts/pagination/link.php
Found the issue with Javascript approach in frontend when using `getListFooter` function. 
Fixed the same issue in Joomla core too https://github.com/joomla/joomla-cms/pull/7319
When using `getListFooter` in frontend, having issue in pagination link because of Javascript.
If we use
```
echo $this->pagination->getListFooter();
```
_Note: Layout or pagination file should not be overrided_
To reproduce this issue can manually use above function in code or if you are using `JPagination` in your component you may check there. 
_There are many other ways to fix it by overriding `JPagination` class and `JLayout` but I think this should be fix in core too._
=> JPagination link href issue in frontend with getListFooter

.travis.yml
right now redCORE in PHP7 is not working. But being PHP7 not yet stable we don't need to send snapshots of the failures. With this modification I'm making travis to not send snapshots on builds other than 5.5
=> Avoid doing snapshot of allow_failure builds

libraries/redcore/layout/file.php
On windows machines the function that tries to detect automatically the active component does not work because paths use \ instead of /.
I have replaced it with `JApplicationHelper::getComponentName();` which should save us work.
=> [fix] component detection does not work on Windows machines

libraries/redcore/browser/browser.php
$router->parse change $uri and crop url 'path' value for current page link, so it must be clone before execution.
=> RSBTB-2408 #comment Fixed wrong redirection when use subfolders in a server

.gitignore, composer.lock, gulp-config.json.dist, gulp-extensions.json, gulpfile.js, package.json
This integrates the joomla-gulp system with redCORE.
To speed things I have used a self hosted repo https://github.com/phproberto/gulp-redcore to store the redcore gulp scripts so they can be reused in any subproject that uses redCORE with:
`npm install gulp-redcore`
Then add the redcore extensions to the list of extensions of the project and system is ready.
=> Gulp build system

libraries/redcore/html/rjquery.php, libraries/redcore/joomla/form/field.php
This is actually just a quick fix for preventing Akeeba from clashing with redCORE.
However, we should review the way these scripts are being loaded.
=> Changed jQuery migrate load order to make sure jQuery scripts load to gether at the top of the document

libraries/redcore/bootstrap.php, libraries/redcore/form/field/childlist.php, libraries/redcore/form/fields/rchildlist.php, libraries/redcore/layouts/fields/rchildlist.php, libraries/redcore/layouts/fields/rlist.php, libraries/redcore/layouts/redcore/field/childlist.php, libraries/redcore/layouts/redcore/field/list.php
This pull request creates a proper base system to migrate redCORE fields. It also adds an AJAX token that will be added automatic to all the `RFormFieldChildlist` fields.
Changes include:
* Fields will be in `libraries/redcore/field` instead of `libraries/redcore/fields` to allow autoloading working.
* Fields classes will include the `R` prefix instead of using Joomla core prefix. So we will use: `RFormFieldChildlist` instead of `JFormFieldRchildlist`. That way autoloading works out of the box and our fields have a better naming. 
* When using fields you have to call them with `type="r.childlist"` (prefix.name) instead of the old `type=rchildlist`.
* redCORE layouts will use the redCORE prefix so we will use `redcore.field.childlist` instead of `fields.rchildlist`. This will ensure that …
=> Automatic ajax tokens for childlist field + base system for new fields

libraries/redcore/helper/currency.php
In another project this `RHelperCurrency::getCurrency()` is called without having a real currency code. This could be solved there by removing calls but I think is ok to also avoid doing queries when a wrong currency has been passed.
This saves me 16 queries:
=> Avoid queries when no currency is received

libraries/redcore/model/list.php
This fixes an issue caused by https://github.com/redCOMPONENT-COM/redCORE/commit/4f823cec4d77eb29d8396fa19c0d4b81510235c3
When no data is received from request the model was forcing all the model state to be an empty array:
```php
$app->setUserState($this->context, $data);
```
That means that if your model is using another context var for something else it gets removed automatically. Let's say that I use something like this in my model's populateState:
```php
$filterProductId = $this->getUserStateFromRequest($this->context . '.product_id', 'product_id');
```
When the page is reloaded that filter (that should be kept in session) is deleted. 
Now I'm only overwritting information for `filter` & `list` which is the only information that is automatically processed from the request by the …
=> Only remove list models context for filter + list

libraries/redcore/model/list.php
Until we find a better solution and due to the issues found in patches that included the form filtering we decided to apply same fix that was applied in core. 
I only modified it to adjust it to our limitField & limitstartField properties.
This should be fully B/C but still has the issue that any filter that we don't want to be exposed can be used.
=> Apply core fix for RModelList

build/gulp-redcore/cli/cli.js, build/gulp-redcore/cli/redcore.js, build/gulp-redcore/components/redcore.js, build/gulp-redcore/libraries/redcore.js, build/gulp-redcore/main.js, build/gulp-redcore/media/redcore.js, build/gulp-redcore/modules/site/redcore_langswitcher.js, build/gulp-redcore/plugins/redpayment/paypal.js, build/gulp-redcore/plugins/system/mvcoverride.js, build/gulp-redcore/plugins/system/redcore.js, build/gulp-redcore/webservices/redcore.js, build/gulp-redcore/webservices/webservices.js
set a absolute path for the process make it more easy to pinpoint where are we instead of standard ../../../../ paths... this will make sure that redCORE gulp scripts work placed in any project folder
=> REDCORE-446_update_gulp_scripts

extensions/plugins/redpayment/paypal/helpers/payment.php
I find it strange that nobody noticed, or maybe nobody is actually using this gaeway... but the callback is not working, as the order_id is mapped to invoice, and not remapped back to retrieve that payment,
=> [fix] Fixed paypal callback

extensions/libraries/redcore/api/hal/hal.php
so basically with this PR we dont populate every missing field with default values, and fields set as null to default value, but instead we leave null as a value capable of passing to the model.
So if the field is not sent (through request) it will be set as null, unless that operation is create then it will take default value.
=> Rsbtb 3588 add a empty field option through api

extensions/components/com_redcore/admin/controllers/webservice.php, extensions/components/com_redcore/admin/layouts/sidebar.bs3.php, extensions/libraries/redcore/menu/menu.php, extensions/libraries/redcore/translation/table.php, extensions/plugins/system/redcore/redcore.php
This PR for 2 point:
**[Fix] Menu doesn't translate:**
Preprocedure this bug:
- Install new language "Vietnamese (vi-VN)".
- Set default site language is "en-GB".
- Translate menu with this new language.
- Enable plugin "Language Filter"
- Enable module "Redcore - Language Switch"
- At home page ("en-GB") => Switch to "vi-VN" => Menu translated.
- At this page ("vi-VN") => Switch to "en-GB" => Menu not transated. => Refresh page => Menu translated.
Reason: It's just happen because the switched language is default so that menu doesn't re-load and keep translated title (In this case is still VN).
**[Improvement] Manage Translate Content**
- In redCORE backend.
- Hide tables which have state "unpublish".
=> Translation improvement

extensions/components/com_redcore/admin/layouts/translation/input.php, extensions/components/com_redcore/admin/layouts/translation/params.php, extensions/components/com_redcore/admin/views/translation/view.html.php, extensions/libraries/redcore/translation/table.php
- Rewrite layout of translate create/edit page for more friendly and clean for end-user.
- Also re-order field follow ordering of xml file.
=> [Improve] Translation create/edit page for more user friendly

extensions/libraries/redcore/layouts/component/admin.bs3.php, extensions/libraries/redcore/layouts/component/admin.php
This [pull request](https://github.com/redCOMPONENT-COM/redCORE/pull/721) partially solved the permissions issue.
When there is no message container you get a JS error like:
`TypeError: messageContainer is null`
Because the message container is not found and joomla core javascript tries to remove messages on it. This ensure that we always have a message container.
=> [fix] missing message container

extensions/libraries/redcore/joomla/form/field.php
Details https://redweb.atlassian.net/browse/REDCORE-509
Besides the changes described in the issue description needed to add the `getLayoutPaths` method too.
To reproduce the issue:
- install joomla 3.7.0 alpha 1 (or joomla latest staging)
- Go to Extensions -> Update and you will see the fatal error
- Apply this patch and no more fatal error.
=> REDCORE-509 fix fatal error on joomla 3.7.0 alpha 1 (or latest staging)

extensions/libraries/redcore/loader/loader.php
redCORE use appends but Joomla uses prepend autoloader. 
So there needs back order for back compatibility.
=> SBRIBE-170 #comment Change priority for load files for compatibility with Joomla priority

extensions/libraries/redcore/html/raccess.php
This is a workaround for selecting usergroups. It is used in cases where
we have large number of usergroups which results in problems with
sending too much inputs (per each usergroup). This fix sends only
selected usergroups instead. Beside class in this PR, it is required to
override admin tpl file under
`administrator/templates/TEMPLATE/html/com_users/user/edit_groups.php`
and change `JHtml::_('access.usergroups', 'jform[groups]',
$this->groups, true);` to `RHtml::_('raccess.usergroups',
'jform[groups]', $this->groups, true);`
=> TRIAX-428 #comment Fix for usergroups list

extensions/libraries/redcore/model/model.php
When more than one component registers the same model name than other component you can get `Cannot instanciate the model %s in component %s` errors.
We have experienced this on a site after upgrading it to Joomla 3.7.0 because Joomla has now a `Fields` model which uses the same name than our `Fields` model.
This should be a fully B/C change because we are already calculating the prefix. The only change is using it to store the lookup folders.
=> [fix] cannot instantiate model with duplicated model names

extensions/libraries/redcore/joomla/form/field.php
can't access the magic properties in twig if __isset is missing
=> [fix] missing isset property for form field class

extensions/libraries/redcore/loader/loader.php
@Kixo @jatitoam There is a problem with MVC override plugin.
It can not use JLoader protected static variables if redCORE loader uses in a project.
It sees variables with the same names from RLoader but they are with different values.
I propose a solution like below - allow RLoader use parent variables and if they do not exist(for example in old Joomla) then use it's own.
Or another way there https://github.com/redCOMPONENT-COM/redCORE/blob/develop/extensions/libraries/redcore/loader/loader.php#L455-L480 add check for each `spl_autoload_register` like 
`if (!is_callable('parent::loadByPsr4'))
{
spl_autoload_register(array('RLoader', 'loadByPsr4'), true, true);
}`
So we register compatibility method just if it is not available from JLoader. Then we will get each autoloads just once. It …
=> Use parent (JLoad) properties if possible

extensions/libraries/redcore/controller/form.php
when the return url is pure sef, without ?, make sure the append string starts with ? instead of &
=> [fix] fixed invalid appending of get var on seo return url
